package com.fptu.math_master.service;

import com.fptu.math_master.dto.response.RoadmapDetailResponse;
import com.fptu.math_master.entity.StudentWish;
import java.util.List;
import java.util.UUID;

/**
 * Service for AI-powered roadmap planning based on student wishes and performance data
 *
 * Uses Gemini AI to:
 * - Analyze student goals and preferences
 * - Prioritize topics based on performance and preferences
 * - Generate personalized learning paths
 * - Create time-based study schedules
 */
public interface RoadmapAIPlannerService {

  /**
   * Generate an AI-powered learning roadmap based on student wishes
   *
   * @param studentId Student identifier
   * @param wish Student's learning wishes and preferences
   * @param subject Subject to learn
   * @return Personalized roadmap generated by AI
   */
  RoadmapDetailResponse generateRoadmapFromWish(UUID studentId, StudentWish wish, String subject);

  /**
   * Generate AI prompt for roadmap planning
   *
   * @param wish Student's wishes
   * @param performanceStats Student's performance statistics
   * @param gradeLevel Grade level
   * @return AI prompt string
   */
  String generateRoadmapPrompt(StudentWish wish, PerformanceStats performanceStats, String gradeLevel);

  /**
   * Parse AI response and extract topic prioritization data
   *
   * @param aiResponse Response from Gemini AI
   * @return Parsed roadmap plan with priorities and recommendations
   */
  AIPlannerResponse parseAIResponse(String aiResponse);

  /**
   * Data class for performance statistics
   */
  class PerformanceStats {
    public UUID studentId;
    public String subject;
    public Double averageAccuracy;
    public List<TopicPerformance> topicStats;
    public Integer totalAssessmentsCompleted;

    public static class TopicPerformance {
      public String topicName;
      public Double accuracy;
      public Integer questionsAttempted;
      public String difficulty;
    }
  }

  /**
   * Response from AI planner
   */
  class AIPlannerResponse {
    public List<PrioritizedTopic> topics;
    public Integer estimatedDays;
    public Integer totalHours;
    public List<String> recommendations;
    public String focusAreas;

    public static class PrioritizedTopic {
      public String title;
      public Integer priority; // -2 (weak), -1 (review), 0 (normal), 1 (interested), 2 (advanced)
      public String difficulty; // EASY, MEDIUM, HARD
      public Integer estimatedHours;
      public String rationale; // Why this topic was prioritized
    }
  }
}
