spring:
  application:
    name: math-master
  devtools:
    restart:
      enabled: false

  datasource:
    url: jdbc:postgresql://ep-green-mouse-ahwgiq0a-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_ZuSN4IPnBd7o
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      data-source-properties:
        sslmode: require
        prepareThreshold: 0
        preparedStatementCacheQueries: 0
        preparedStatementCacheSizeMiB: 0

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

server:
  port: 8080

# ================================
# JWT
# ================================
jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  valid-duration: 3600
  refreshable-duration: 36000

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO

# ================================
# Springdoc OpenAPI Configuration
# ================================
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

# ================================
# Username and Password
# ================================
app:
  init:
    enabled: true

    admin:
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
      email: ${ADMIN_GMAIL:admin@mathmaster.edu.vn}
      fullname: ${ADMIN_FULLNAME:System Administrator}

    student:
      username: ${STUDENT_USERNAME:student}
      password: ${STUDENT_PASSWORD:student123}
      email: ${STUDENT_GMAIL:student@mathmaster.edu.vn}
      fullname: ${STUDENT_FULLNAME:Student User}

    teacher:
      username: ${TEACHER_USERNAME:teacher}
      password: ${TEACHER_PASSWORD:teacher123}
      email: ${TEACHER_GMAIL:teacher@mathmaster.edu.vn}
      fullname: ${TEACHER_FULLNAME:Teacher User}

# ================================
# PayOS Configuration
# ================================
payos:
  client-id: 3af710f4-e502-4ddb-b99d-72ffa68f8423
  api-key: b5087001-a7a7-4f60-af06-c941f374e5aa
  checksum-key: 7a6fd4e43ca930c32838b42f7976dd13c746ccc236a678b95585b68da743a5a4
  return-url: ${PAYOS_RETURN_URL:http://localhost:3000/payment/success}
  cancel-url: ${PAYOS_CANCEL_URL:http://localhost:3000/payment/cancel}
